
import * as express from 'express';
import { Application } from 'express';
import { readAllLessons } from './read-all-lessons.route';
import { addPushSubscriber } from './add-push-subscriber.route';
import { sendNewsletter } from './send-newsletter.route';
const bodyParser = require('body-parser');

const webpush = require('web-push');

/**
 * GENERATED by command web-push generate-vapid-keys --json
 */
const vapidKeys = {
  'publicKey': 'BLAouOTmhAgBYE4XnNteN07SelQeN8sKS26f9JXTkLkUgxdQI-XcO17xHMLas2uPIjxg5PiLPV2bWyuke1moqVI',
  'privateKey': 'RYmD2BETTqCtkUWOEd-OVJXapBlP5esK0ekg8916Q1s'
};


webpush.setVapidDetails(
  'mailto:mateussilveiracosta98@gmail.com',
  vapidKeys.publicKey,
  vapidKeys.privateKey
);




const app: Application = express();


app.use(bodyParser.json());


// REST API
app.route('/api/lessons')
  .get(readAllLessons);

app.route('/api/notifications')
  .post(addPushSubscriber);

app.route('/api/newsletter')
  .post(sendNewsletter);



// launch an HTTP Server
const httpServer = app.listen(9000, () => {
  console.log('HTTP Server running at http://localhost:' + httpServer.address()['port']);
});









